server:
  port: 7000
spring:
  redis:
    host: 121.36.230.118
    password: justmiss.redis
bot:
#  image-home: 'd://share/'
  image-home: 'data/'
  pixiv-api: 'http://207.148.95.137:7000'
  netLog: 'netLog'
  qq: 212746897
  password: justmiss.qq


